version: '3'

services:
  web:
    image: nginx:1.19.7-alpine
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.0.5-fpm-alpine
    volumes:
        - ./code:/code